
use mysql;
ALTER USER 'root'@'localhost' IDENTIFIED BY '';
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';

CREATE DATABASE IF NOT EXISTS cvm CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE USER IF NOT EXISTS 'cvm'@'localhost' IDENTIFIED BY 'cvm123';
ALTER USER 'cvm'@'localhost' IDENTIFIED WITH mysql_native_password BY 'cvm123';

GRANT ALL PRIVILEGES ON cvm.* TO 'cvm'@'localhost';

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS `cvm`.`FI_CAD` (
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_REG` DATE,
  `DT_CONST` DATE,
  `DT_CANCEL` DATE,
  `SIT` VARCHAR(40),
  `DT_INI_SIT` DATE,
  `DT_INI_ATIV` DATE,
  `DT_INI_EXERC` DATE,
  `DT_FIM_EXERC` DATE,
  `CLASSE` VARCHAR(100),
  `DT_INI_CLASSE` DATE,
  `RENTAB_FUNDO` VARCHAR(100),
  `CONDOM` VARCHAR(15),
  `FUNDO_COTAS` CHAR(1),
  `FUNDO_EXCLUSIVO` CHAR(1),
  `TRIB_LPRAZO` CHAR(1),
  `INVEST_QUALIF` CHAR(1),
  `TAXA_PERFM` FLOAT,
  `INF_TAXA_PERFM` VARCHAR(400),
  `TAXA_ADM` DOUBLE,
  `INF_TAXA_ADM` VARCHAR(400),
  `VL_PATRIM_LIQ` DECIMAL(18, 2),
  `DT_PATRIM_LIQ` DATE,
  `DIRETOR` VARCHAR(100),
  `CNPJ_ADMIN` VARCHAR(20),
  `ADMIN` VARCHAR(100),
  `PF_PJ_GESTOR` CHAR(2),
  `CPF_CNPJ_GESTOR` VARCHAR(20),
  `GESTOR` VARCHAR(100),
  `CNPJ_AUDITOR` VARCHAR(20),
  `AUDITOR` VARCHAR(100),
  `CNPJ_CUSTODIANTE` VARCHAR(20),
  `CUSTODIANTE` VARCHAR(100),
  `CNPJ_CONTROLADOR` VARCHAR(20),
  `CONTROLADOR` VARCHAR(100),
  PRIMARY KEY (`CNPJ_FUNDO`) )
ENGINE = InnoDB;

 CREATE TABLE IF NOT EXISTS `cvm`.`FI_DOC_INF_DIARIO` (
   `CNPJ_FUNDO` VARCHAR(20) NOT NULL ,
   `DT_COMPTC` DATE NOT NULL,
   `VL_TOTAL` DECIMAL(18, 2) NOT NULL,
   `VL_QUOTA` DECIMAL(28, 12) NOT NULL,
   `VL_PATRIM_LIQ` DECIMAL(18, 2),
   `CAPTC_DIA` DECIMAL(18, 2),
   `RESG_DIA` DECIMAL(18, 2),
   `NR_COTST` INTEGER UNSIGNED,
   PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
 ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`FIE_CAD` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_REG` DATE,
  `DT_CONST` DATE,
  `DT_CANCEL` DATE,
  `SIT` VARCHAR(40),
  `DT_INI_SIT` DATE,
  `DT_INI_ATIV` DATE,
  `DT_INI_EXERC` DATE,
  `DT_FIM_EXERC` DATE,
  `CNPJ_ADMIN` VARCHAR(20),
  `ADMIN` VARCHAR(100),
  `PF_PJ_GESTOR` CHAR(2),
  `CPF_CNPJ_GESTOR` VARCHAR(20),
  `GESTOR` VARCHAR(100),
  `CNPJ_AUDITOR` VARCHAR(20),
  `AUDITOR` VARCHAR(100),
  PRIMARY KEY (`CNPJ_FUNDO`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`FIE_MEDIDAS` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `VL_PATRIM_LIQ` DECIMAL(18, 2),
  `NR_COTST` INTEGER UNSIGNED,
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_1` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `TP_TITPUB` VARCHAR(50),
  `CD_ISIN` VARCHAR(12),
  `CD_SELIC` VARCHAR(6),
  `DT_EMISSAO` DATE,
  `DT_VENC` DATE,
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_2` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `CNPJ_FUNDO_COTA` VARCHAR(20),
  `NM_FUNDO_COTA` VARCHAR(100),
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_3` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `CD_SWAP` VARCHAR(50),
  `DS_SWAP` VARCHAR(100),
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_4` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `CD_ATIVO` VARCHAR(100),
  `DS_ATIVO` VARCHAR(100),
  `CD_ISIN` VARCHAR(12),
  `DT_INI_VIGENCIA` DATE,
  `DT_FIM_VIGENCIA` DATE,
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_5` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `CNPJ_EMISSOR` VARCHAR(20),
  `EMISSOR` VARCHAR(200),
  `DT_VENC` DATE,
  `TITULO_POSFX` CHAR(1),
  `CD_INDEXADOR_POSFX` VARCHAR(50),
  `DS_INDEXADOR_POSFX` VARCHAR(100),
  `PR_INDEXADOR_POSFX` DECIMAL(10, 6),
  `PR_CUPOM_POSFX` DECIMAL(10, 6),
  `PR_TAXA_PREFX` DECIMAL(10, 6),
  `RISCO_EMISSOR` CHAR(1),
  `AG_RISCO` VARCHAR(200),
  `DT_RISCO` DATE,
  `GRAU_RISCO` CHAR(6),
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_6` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `PF_PJ_EMISSOR` CHAR(2),
  `CPF_CNPJ_EMISSOR` VARCHAR(20),
  `EMISSOR` VARCHAR(200),
  `DT_VENC` DATE,
  `TITULO_POSFX` CHAR(1),
  `CD_INDEXADOR_POSFX` VARCHAR(50),
  `DS_INDEXADOR_POSFX` VARCHAR(100),
  `PR_INDEXADOR_POSFX` DECIMAL(10, 6),
  `PR_CUPOM_POSFX` DECIMAL(10, 6),
  `PR_TAXA_PREFX` DECIMAL(10, 6),
  `TITULO_CETIP` CHAR(1),
  `TITULO_GARANTIA` CHAR(1),
  `CNPJ_INSTITUICAO_FINANC_COOBR` VARCHAR(20),
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_7` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `INVEST_COLETIVO` CHAR(1),
  `INVEST_COLETIVO_GESTOR` CHAR(1),
  `EMISSOR` VARCHAR(200),
  `DT_VENC` DATE,
  `CD_PAIS` CHAR(3),
  `PAIS` VARCHAR(100),
  `CD_BV_MERC` CHAR(6),
  `BV_MERC` VARCHAR(100),
  `CD_ATIVO_BV_MERC` CHAR(12),
  `RISCO_EMISSOR` CHAR(1),
  `AG_RISCO` VARCHAR(200),
  `DT_RISCO` DATE,
  `GRAU_RISCO` CHAR(6),
  `DS_ATIVO_EXTERIOR` VARCHAR(50),
  `QT_ATIVO_EXTERIOR` DECIMAL(19, 0),
  `VL_ATIVO_EXTERIOR` FLOAT,
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_BLC_8` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `TP_APLIC` VARCHAR(150),
  `TP_ATIVO` VARCHAR(150),
  `EMISSOR_LIGADO` CHAR(1),
  `TP_NEGOC` VARCHAR(24),
  `QT_VENDA_NEGOC` DECIMAL(22, 6),
  `VL_VENDA_NEGOC` DECIMAL(18, 2),
  `QT_AQUIS_NEGOC` DECIMAL(22, 6),
  `VL_AQUIS_NEGOC` DECIMAL(18, 2),
  `QT_POS_FINAL` DECIMAL(22, 6),
  `VL_MERC_POS_FINAL` DECIMAL(18, 2),
  `VL_CUSTO_POS_FINAL` DECIMAL(18, 2),
  `DT_CONFID_APLIC` DATE,
  `DS_ATIVO` VARCHAR(1000),
  `PF_PJ_EMISSOR` CHAR(2),
  `CPF_CNPJ_EMISSOR` VARCHAR(20),
  `EMISSOR` VARCHAR(150),
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cvm`.`CDA_FI_PL` (
  `TP_FUNDO` VARCHAR(15),
  `CNPJ_FUNDO` VARCHAR(20) NOT NULL,
  `DENOM_SOCIAL` VARCHAR(100),
  `DT_COMPTC` DATE NOT NULL,
  `VL_PATRIM_LIQ` DECIMAL(24, 2),
  PRIMARY KEY (`CNPJ_FUNDO`, `DT_COMPTC`) )
ENGINE = InnoDB;

